

services:
  scrapy:
    build:
      context: ./fangzhou-spider  
      dockerfile: Dockerfile
    container_name: scrapy_container
    volumes:
      - $HOME/v2/logs/scrapy:/app/logs
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - fangzhou_network
    restart: "no"

  mongo:
    image: mongo:5.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - $HOME/v2/mongodb/data:/data/db
    networks:
      - fangzhou_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 2s
      retries: 5

  web:
    build:
      context: ./fangzhou-backend
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - static_volume:/app/static
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=web,nginx,localhost,127.0.0.1
    ports:
      - "8000:8000"
    depends_on:
      - scrapy
    networks:
      - fangzhou_network

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    volumes:
      - ./fangzhou-frontend/dist:/usr/share/nginx/html
      - static_volume:/app/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - fangzhou_network

volumes:
  static_volume:

networks:
  fangzhou_network:
    driver: bridge
